spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
    password: secretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Временно, чтобы не создавал таблицы
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

# Временно отключим всё лишнее
logging:
  level:
    org.springframework: WARN
    com.zaxxer.hikari: INFO
